# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  input:          GFM

# Permalinks
permalink:        pretty

# Setup
title:            Modulo: Elaborazione dati
description:      'Controllo biologico dei processie dei prodotti dell'industria'
url:              http://mchiapello.github.io/2019_Master_Course
baseurl:          /2019_Master_Course
email:            chiapello.m@gmail.com
feedbackurl:      https://docs.google.com/forms/d/e/1FAIpQLSdV_polFmoukgjcs1IC0Dd4iO1rdgwFnOds28xC_ma_z4tNIw
author:
  name:           'Marco Chiapello'
  url:            https://twitter.com/marpello1980

github:
  repo:           https://mchiapello.github.io/2019_Master_Course
  #               Be sure the 'Issues' feature is activated in 'Settings'
