# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  input:          GFM

# Permalinks
permalink:        pretty

# Setup
title:            Master course
description:      'Teaching the tools to get computers to do cool science'
url:              http://mchiapello.github.io/2019_Master_Course
baseurl:          /2019_Master_Course
email:            chiapello.m@gmail.com
feedbackurl:      polleverywhere.com/multiple_choice_polls/KznOEBvSAnahmt7
author:
  name:           'Marco Chiapello'
  url:            https://twitter.com/marpello1980

github:
  repo:           https://github.com/mchiapello/2019_Master_Course
  #               Be sure the 'Issues' feature is activated in 'Settings'
